### ISSUE TITLE
ICU Version 71.1 is missing

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/icu#267]
ICU Version 71.1 is not available.

https://github.com/unicode-org/icu/releases/tag/release-71-1

Also, the CPE seems weird?

I plan to test out the new dependencies workflow on this repo soon.

**Comment by fg-j** [comment]
It seems like the dep server build-and-upload step failed for this version. @paketo-buildpacks/dependencies, can someone rerun [this job](https://github.com/paketo-buildpacks/dep-server/runs/5856347212?check_suite_focus=true)?
